services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf-dostochka
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - stirling_configs:/configs
      - stirling_customFiles:/customFiles
      - stirling_logs:/logs
      - stirling_tessdata:/usr/share/tessdata
      - stirling_pipeline:/pipeline
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLE_LOGIN=true
      - SECURITY_CSRFDISABLED=true
      - SECURITY_INITIALLOGIN_USERNAME=dostochka_admin
      - SECURITY_INITIALLOGIN_PASSWORD=DostochkaPDF2024!
      - API_KEY_ENABLED=true
      - API_KEYS=dostochka-n8n-api-2024,dostochka-backup-key-456
      - UI_APPNAME=Dostochka PDF Processing
      - UI_HOMEDESCRIPTION=Secure PDF processing service
      - UI_APPNAMENAVBAR=Dostochka PDF
      - MAX_FILE_SIZE=1000MB
      - METRICS_ENABLED=true
      - UI_DEFAULTLOCALE=ru_RU
      - ALLOW_GOOGLE_VISIBILITY=false
      - HIDE_DEFAULT_LOGIN=false
      - SYSTEM_ROOTURIPATH=/
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - nginx_proxy_manager_default
      - default
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/v1/info/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  img-normalizer:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: img-normalizer:1.0
    container_name: img-normalizer
    restart: unless-stopped
    expose:
      - "8081"
    environment:
      - API_KEY=img-normalizer-secret-2025
    networks:
      - nginx_proxy_manager_default
      - default
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  stirling_configs:
  stirling_customFiles:
  stirling_logs:
  stirling_tessdata:
  stirling_pipeline:

networks:
  nginx_proxy_manager_default:
    external: true
  default:
    driver: bridge
